Print Tab(25); "WARFISH"
Print Tab(20); "CREATIVE COMPUTING"
Print Tab(18); "MORRISTOWN, NEW JERSEY"
Print
Print
Print
Print
Dim A$(72)
Q0 = Rnd(1)
ASK1:
Print "DO YOU DESIRE THE RULES OF WARFISH ";
Input X$
If X$ = "NO" Then GoTo GSTART
If X$ = "YES" Then GoTo RULES
Print "YES OR NO ONLY, PLEASE."
GoTo ASK1
RULES:
Print
Print "YOU COMMAND AN AMERICAN SUBMARINE THAT BEEN SENT OUT"
Print "TO ATTACK JAPANESE SHIPS AT SEA DURING WORLD WAR TWO"
Print
Print "THE ORDERS THAT CAN BE GIVEN ARETHE FOLLOWING:"
Print "PERISCOPE - TO SEARCH FOR JAPANESE SHIPS"
Print "TORPEDO - TO LAUNCH TORPEDOES AT JAPANESE SHIPS"
Print "DIVE - TO EASCAPE JAPANESE SHIPS THAT ARE ATTACKING"
Print
Print "THESE ARE SOME HISTORIC U.S. NAVY SUBMARINES -"
Print "      TAUTOG, SILVERSIDES, CAVALLA, BLUEFISH, THRESHER"
Print "      SWORDFISH, FLASHER, TROUT, ARCHER"
Print "SELECT ONE OF THE ABOVE, OR USE A NAME OF YOUR OWN CHOICE"
GSTART:
Print "PRINT THE NAME OF YOUR SUBMARINE ";
Input A$
T = 26
D = Int(Rnd(1) * 10)
If D < 6 Then GoTo 330
If D <> 6 And D <> 7 Then GoTo SPARK1
R$ = "DESTROYER"
W = 2100
SPARK1:
If D <> B Then GoTo SPARK2
R$ = "DESTROYER ESCORT"
W = 1350
SPARK2:
If D <> 9 Then GoTo SPARK3
R$ = "TORPEDO BOAT"
W = 70
SPARK3:
If D = 6 Or D = 7 Then GoTo SPARK4
Q = 1
GOTO 314
SPARK4:
Q = 2
Print
Print
Print "JAPANESE "; R$; " IS ATTACKING"
If D >= 6 Then GoTo ORDERS
A = Int(Rnd(1) * 10)
ORDER:
Print
Print
Print "ORDERS, COMMANDER ";
Input C$
C$ = Mid$(C$, 1, 1)
If C$ = "P" Then GoTo 420
If C$ = "T" Then GoTo 780
If C$ = "D" Then GoTo 990
GoTo 360
If D > 5 Or Q > 0 Then 760
If A >= 4 Then 470
R$ = "FREIGHTER"
IF A<>0 THEN A<>1 THEN 450
WW=6500
IF A<>2 THEN 460
W=7500
IF A<>3 THEN 470
W=8100
IF A<>7 AND A<>8 THEN 490
R$="TANKER"
IF A<>8 THEN 485
W=10000
GOTO 490
W=9500
IF A<>4 AND A<>5 THEN 510
R$="TRANSPORT"
IF A<5> THEN 505
W=11500
GOTO 510
W=8800
IF A<>6 THEN 530
R$="AMMUNITION SHIP"
W=9650
IF A>=9 OR A=6 540
Q=1
IF A<>6 THEN 550
Q=1
IF A<9 THEN 760
E=INT(RND(1)*10)
IF E<>0 THEN 590
R4="BATTLESHIP"
W=33500
IF E<>1 THEN 610
R$="AIRCRAFT CARRIER"
